---
title: "Assignment 5"
author: "Nathan Redon"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r makefig, include = TRUE}
## Dependencies
# install.packages(c("tidyverse","ggplot2","here"))
packages <- c("tidyverse", "ggplot2", "here")
lapply(packages, library, character.only = TRUE)

## Get data
df <- read.csv(here("data","siscowet.csv"))

## Wrangle data
df$wgt[541] <- 1580 # "Fix" the crazy outlier just for this assignment
df$locID <- as.factor(df$locID)

## Make exploratory figure, how did sample depth vary by location?
plot(pnldep ~ locID, data = df) # Check out depth, looks like there's some variability

## Make expository figure
# reorder factor levels by length to best represent spread
df$locID = with(df, reorder(locID, len))

# draw plot
(p <- df %>%
  ggplot(aes(x = locID, y = pnldep, fill = locID) + 
    geom_violin(trim = F) +
    xlab("Location") +
    theme(legend.position="none") +
    xlab("Location") +
    ylab("Depth of gillnet panel (m)")))
  
p <- ggplot(df, aes(x = factor(locID), y = pnldep))
p + geom_violin(aes(fill = locID)) +
    scale_fill_viridis_d() +
    xlab("Site") +
    ylab("Gillnet\npanel\ndepth(m)") +
    labs(color = "Penguin Species",
         title = "<b>Variability in gillnet panel depth targeting Siscowet Lake Trout in Lake Superior</b><br>
           <span style = 'font-size:10pt'>Variability across four sites, <span       style='color:#410155'>Grand Marais</span>, <span style='color:#3A6890'>Deer Park </span>, <span style='color:#4DB777'>Blind Sucker</span>, and <span style='color:#FAE600'>Little Lake Harbor</span>.</span>")+
    theme_minimal() + 
    theme(
      plot.title.position = "plot",
      plot.title = element_textbox_simple(size=12),
      axis.title.x = element_blank(),
      axis.ticks.x = element_blank(),
      axis.text.x = element_blank(),
      axis.title.y = element_text(angle = 0, vjust = .5,size=14),
      axis.text = element_text(size=12),
      legend.position="none")

  

# violin plot with mean points
p + stat_summary(fun.y=mean, geom="point", shape=23, size=2)
# violin plot with median points
p + stat_summary(fun.y=median, geom="point", size=2, color="red")
# summary stats
p + geom_boxplot(width=0.1)
p + stat_summary(fun.data=mean_sdl, mult=1, 
                 geom="pointrange", color="red")
p + geom_jitter(shape=16, position=position_jitter(0.2))
p + scale_color_viridis_d()




```
